language: python
cache: pip
sudo: false

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - pypy3
 - pypy
 - 2.7
 - 3.6
 - 3.5
 - 3.4

install:
 - pip install -U flake8

script:
 # Static analysis
 - flake8

 # Validate
 - python validate-json.py

matrix:
  fast_finish: true
