language: python

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - pypy3
 - pypy
 - 2.7
 - 3.6
 - 3.5
 - 3.4

sudo: false

install:
 - pip install pycodestyle pyflakes

script:
 # Static analysis
 - pyflakes .
 - pycodestyle --statistics --count .

 # Validate
 - python validate-json.py

matrix:
  fast_finish: true
